---
  - name: updating system
    apt:
      upgrade: yes
      update_cache: yes
      
  - name: Create tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 777
      
  - name: Unarchive a tomcat file that needs to be downloaded
    unarchive:
      src: http://apache.spinellicreations.com/tomcat/tomcat-8/v8.5.57/bin/apache-tomcat-8.5.57.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      
  - name: Insert/Update block in /home/ubuntu/.bashrc
    blockinfile:
      path: /home/ubuntu/.bashrc
      block: |
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        export CATALINA_HOME=/opt/tomcat/apache-tomcat-8.5.32
      
  - name: register changes
    shell: . /home/ubuntu/.bashrc
    
  
    
  - name: activate Tomcat
    shell: $CATALINA_HOME/bin/startup.sh
